// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudentHousing.Data;
using System;

namespace StudentHousing.Migrations
{
    [DbContext(typeof(ListingDbContext))]
    [Migration("20180408041425_ImplementUser")]
    partial class ImplementUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentHousing.Models.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Image");

                    b.Property<int?>("ListingModelId");

                    b.HasKey("Id");

                    b.HasIndex("ListingModelId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("StudentHousing.Models.ListingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("Address3");

                    b.Property<string>("Amendities");

                    b.Property<decimal>("Bathroom");

                    b.Property<decimal>("Bedroom");

                    b.Property<string>("City");

                    b.Property<string>("ContactName");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<decimal>("DownPayment");

                    b.Property<string>("Email");

                    b.Property<int>("Kitchen");

                    b.Property<string>("MyProperty");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PeopleSignedUp");

                    b.Property<bool>("PetFriendly");

                    b.Property<string>("PhoneNumber");

                    b.Property<decimal>("Rent");

                    b.Property<bool>("RentIncludeUtil");

                    b.Property<int>("RoomAvailable");

                    b.Property<decimal>("SqrFeet");

                    b.Property<string>("State");

                    b.Property<decimal>("Utilities");

                    b.Property<int>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StudentHousing.Models.Images", b =>
                {
                    b.HasOne("StudentHousing.Models.ListingModel")
                        .WithMany("Images")
                        .HasForeignKey("ListingModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
